version: '3.8'
services:
  db:
    image: postgres:15
    container_name: notes_db
    environment:
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: notes_pass
      POSTGRES_DB: notesdb
      TZ: "America/Argentina/Buenos_Aires"   # ← clave
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
